[package]
name = "wyrd-diff-tauri"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
publish.workspace = true

[build-dependencies]
tauri-build.workspace = true

[dependencies]
tauri.workspace = true
anyhow.workspace = true
tokio.workspace = true
wyrd-diff-api.workspace = true
wyrd-diff-core.workspace = true
